#!/bin/sh
# Copyright 2021 ecodeclub
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# git test pre-push hook
#
# To use, store as .git/hooks/pre-push inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

# Pre-push configuration

sh "$(pwd)/scripts/cicd/unit-testing.sh"
if [ $? -ne 0 ]; then
  exit 1
fi

sh "$(pwd)/scripts/cicd/end-to-end-testing.sh"
if [ $? -ne 0 ]; then
  exit 1
fi