version: "3"
services:
  kafka0:
   image: 'bitnami/kafka:3.6.0'
   ports:
     - '9092:9092'
     - '9094:9094'
   environment:
     - KAFKA_CFG_NODE_ID=0
     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
     - KAFKA_CFG_PROCESS_ROLES=controller,broker
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka0:9094,EXTERNAL://localhost:9094
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER